### ISSUE TITLE
Final Exam

### ISSUE THREAD

**Issue by Sherry-Younan** [wbadry/MTE506#10]
Good evening,

For all the Matlab work including the coding parts, is there a probability that we will have any question on them in our final exam or they were just for classwork as announced before along the term ?
We asked Dr.Mohamed about this in his last meeting but we couldn't get a clear answer, if possible for us to have a clear answer about this we would be very thankful.

**Comment by wbadry** [comment]
Dear Sherry,
I regret to inform you that I won't be able to inquire about the exam since it is set By Dr. Mohamed Ibrahim. Therefore, he is the one to be able to answer such an inquiry.

**Comment by Sherry-Younan** [comment]
Okay, Thank You.
