### ISSUE TITLE
some mistakes 

### ISSUE THREAD

**Issue by Mohaned-58329** [wbadry/MTE506#4]
Good morning
i didn't receive from you if you received the assignment or not and i told you i got some problems and explained it in messenger . Thank you

**Comment by wbadry** [comment]
@Mohaned-58329 
Your assignment status was updated

**Comment by Mohaned-58329** [comment]
yes, i explained it in messenger because i was uploaded wrong file with same name i removed it and uploaded the correct one and you can check the date of RC circuit . Thank You
