### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by wbadry** [wbadry/MTE506#5]
The root locus is not the solution for s-domain to z-domain mapping. You should use a sketch to map points between the two domains.

**Comment by mohamed-58508** [comment]
@wbadry 
this isn't the root loucs, the left column represents the location of the pole in the s domain while the right column represents the same pole in the z domain. 
this is what i understood what i was supposed to do showing the pole in both domains.
is that whats required or did i misunderstand something ?

**Comment by wbadry** [comment]
![S-Poles](https://user-images.githubusercontent.com/5664750/78599952-5364fc80-7852-11ea-8372-942cfa8769c4.png)
![Z-Poles](https://user-images.githubusercontent.com/5664750/78599956-54962980-7852-11ea-9b14-84fb60384b62.png)
