### ISSUE TITLE
Final exam

### ISSUE THREAD

**Issue by AhmedMuhamed97** [wbadry/MTE506#9]
Good morning.
First I'm sorry if I'm bothering you but I and my colleagues asked Dr.Mohamed Ibrahem about the final exam marks and how it will be..and we asked him if the final exam could be from 60 marks and the classworks from 90 and he said he will look into this. Dr.Mohamed didn't reply till now and we are calling him for days and he doesn't answer.
So we will be thankful if you may help us understand what will happen.
Thank you.

**Comment by wbadry** [comment]
Dear Ahmed,
You can always post any questions anytime, This is the purpose of having Github to provide a better way to communicate.

Regarding your request, unfortunately, the university restricted classwork to be considered only before the **15th of March** which won't help any of your colleagues. The decision was to **discard any classwork mark** and to assign **150 marks only on final exam** on all courses for graduates (_I received this response from the principal of faculty control_, **Dr. Mohamed Saleh)**.

I already submitted your classwork to Prof. Mohamed Ibrahim and he is the one to conduct any plea to faculty regarding any changes.

**Comment by AhmedMuhamed97** [comment]
Thank you for your time and replying.

But it is difficult to have one chance with 150 mark and go to final with no information about, so may you help us reach Dr.Mohamed?
And if you can't and if it's appropriate I and my colleagues would like to know if the final exam splits in half between you and Dr.Mohamed and which part is the bigger

Thank you.

**Comment by wbadry** [comment]
You may directly contact Prof. Mohamed Hamdy.
